//
// Created by Oscar Guevara Viveros on 7/26/26.
//

#ifndef BICHROMATICGEOMETRICSPANNER_SPANNERBUILDER_H
#define BICHROMATICGEOMETRICSPANNER_SPANNERBUILDER_H


class SpannerBuilder
{
};


#endif //BICHROMATICGEOMETRICSPANNER_SPANNERBUILDER_H
